apiVersion: v1
kind: Pod
metadata:
  name: webapp-front-0
  labels: 
    app: v1-blue
spec:
  containers:
  - name: web
    image: fabioreina/webapp:v1
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-front-1
  labels: 
    app: v2-green
spec:
  containers:
  - name: web
    image: fabioreina/webapp:v2
    ports:
    - containerPort: 80
    
