apiVersion: apps/v1
kind: ReplicaSet 
metadata:
  name: webapp-replicaset
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: web
  template:
      metadata:
        labels:
          app: web
      spec:
        containers:
        - name: web
          image: fabioreina/webapp:v1
          ports:
          - containerPort: 80
   
